from pathlib import Path
import json
root=Path(__file__).parent/'dist'
services=[('Haircut & styling','A fresh shape, a soft finish, a look that feels like you.','350','hair'),('Party makeup','Thoughtfully matched shades for your next special occasion.','1,500','makeup'),('Bridal makeup','A personal consultation for your ceremony and celebration.','6,000','bridal'),('Hair spa','A little time for your hair. A lot of care in every step.','800','care'),('Facial & skin care','Choose a facial with guidance for your skin and comfort.','700','skin'),('Threading & grooming','The finishing touches to your everyday beauty routine.','60','grooming')]
courses=[('Makeup artistry','Skin preparation, shade matching, everyday looks, party makeup and bridal foundations.','makeup'),('Haircut & styling','Sectioning, basic cuts, blow-drying, finishing and occasion styling.','hair'),('Beauty & salon essentials','Client consultation, hygiene, threading, facial fundamentals and salon etiquette.','beauty')]
def btn(label,kind='general',item='',cls='button',href=None):
    return f'<a class="{cls}" href="{href or "https://wa.me/919101035255"}" '+(f'data-enquiry="{kind}" data-item="{item}"' if not href else '')+f'>{label}</a>'
def heading(k,t,sub=''):
    return f'<div class="section-heading reveal"><span class="eyebrow">{k}</span><h2>{t}</h2>'+ (f'<p>{sub}</p>' if sub else '')+'</div>'
def servicecards(all=True):
    return '<div class="service-grid">'+''.join(f'<article class="service-card reveal {"from-left" if i%2==0 else "from-right"}"><span class="service-number">0{i+1}</span><span class="service-icon" aria-hidden="true">{["✂","◌","✧","≈","◇","⌁"][i]}</span><h3>{s[0]}</h3><p>{s[1]}</p>{btn("Enquire about this service","service",s[0],"text-link")}</article>' for i,s in enumerate(services if all else services[:3]))+'</div>'
def pricing():
    return '<section class="section price-section" id="pricing">'+heading('A LITTLE SELF-CARE','Your next look.<br><em>Your kind of care.</em>','Sample starting rates for this demo. Confirm current salon prices on WhatsApp.')+'<div class="price-grid">'+''.join(f'<article class="price-card reveal {"from-left" if i%2==0 else "from-right"} {"featured" if i==2 else ""}">'+('<span class="featured-label">FOR YOUR SPECIAL DAY</span>' if i==2 else '')+f'<span class="eyebrow">{s[0]}</span><div class="price"><small>from</small> ₹{s[2]}</div><p>{s[1]}</p>{btn("Enquire about "+s[0].lower(),"service",s[0])}</article>' for i,s in enumerate(services[:3]))+'</div><div class="price-list reveal">'+''.join(f'<div><span>{s[0]}</span><strong>From ₹{s[2]}</strong>{btn("Ask about this","service",s[0],"text-link")}</div>' for s in services[3:])+'</div><p class="fineprint">Final charges depend on the consultation, hair length, selected look and service requirements.</p></section>'
def training():
    return '<section class="section training-section" id="training">'+heading('ANJALI TRAINING CENTRE','Make beauty<br><em>your skill.</em>','Practical beauty training for women who want to learn, create and grow.')+'<div class="course-grid">'+''.join(f'<article class="course-card reveal {"from-left" if i%2==0 else "from-right"}"><span class="eyebrow">LEARNING PATH / 0{i+1}</span><h3>{c[0]}</h3><p>{c[1]}</p><ul><li>Guided practical learning</li><li>Consultation & hygiene fundamentals</li><li>Ask about batches, duration & fees</li></ul>{btn("Enquire about this course","course",c[0],"button outline")}</article>' for i,c in enumerate(courses))+'</div></section>'
def contactform():
    return '<div class="enquiry-panel reveal"><div><span class="eyebrow">LET’S TALK</span><h2>Your look.<br><em>Your enquiry.</em></h2><p>Tell us what you have in mind. Your choices are included in your WhatsApp message.</p><a class="contact-number" href="tel:+919101035255">9101035255</a><p>Abhayapuri, Assam<br>Ladies salon & beauty training</p></div><form id="enquiry-form"><div class="form-row"><label>Your name<input name="name" autocomplete="name" placeholder="Enter your name" required maxlength="80"></label><label>Enquiry type<select name="type" id="enquiry-type"><option value="appointment">Salon appointment</option><option value="course">Training course</option><option value="general">General enquiry</option></select></label></div><label id="selection-label">Service or course<select name="selection" id="enquiry-selection"></select></label><div class="form-row"><label>Preferred date (optional)<input type="date" name="date"></label><label>Preferred time (optional)<input type="time" name="time"></label></div><label>Your message<textarea name="message" rows="3" placeholder="Your preferred look, course questions or any special requests…" maxlength="1500"></textarea></label><button class="button" type="submit">Continue on WhatsApp</button><p class="form-note">Opens WhatsApp with your message. Your appointment is confirmed only after the salon replies.</p><p id="form-status" role="status"></p></form></div>'
hero='''<section class="hero"><div class="hero-copy"><span class="eyebrow load-text">HAIR. BEAUTY. YOU.</span><h1 class="load-text">Beautiful hair.<br>Confident you.<br><em>Let’s make it happen.</em></h1><p class="load-text">Your ladies salon in Abhayapuri. From a fresh haircut to your wedding-day glow, enjoy care that’s all about you.</p><div class="hero-actions load-text">'''+btn('LET’S SHINE','appointment')+btn('Explore training',href='/training/',cls='text-link')+'''</div><div class="hero-notes load-text"><div><span>✂</span><p>Hair & beauty<br><small>Made personal</small></p></div><div><span>✧</span><p>Learn with us<br><small>Beauty training for women</small></p></div></div></div><div class="hero-visual"><div class="portrait-arch"></div><img src="/assets/stylist.webp" alt="Indian female hairstylist holding salon scissors and a comb" fetchpriority="high" width="1024" height="1536"><div class="portrait-tag">EXCLUSIVELY FOR LADIES</div><div class="portrait-caption"><span>YOUR BEAUTY, YOUR WAY</span><strong>Salon care.<br>Creative learning.</strong></div></div></section>'''
intro='<section class="section intro">'+heading('WELCOME TO ANJALI','A little change.<br><em>A lovely difference.</em>')+'<div class="intro-copy reveal from-right"><p>A new cut. A celebration-ready look. A moment just for yourself. Anjali Super Salon and Training Centre brings ladies salon services and practical beauty learning together in Abhayapuri, Assam.</p><p>Visit for your next hair or beauty appointment, or speak to us about learning makeup, haircutting and salon essentials.</p>'+btn('Get to know us',href='/about/',cls='text-link')+'</div></section>'
process='<section class="section process">'+heading('AN EASY START','From a thought<br><em>to your next look.</em>')+'<div class="steps">'+''.join(f'<article class="reveal"><span>0{i+1}</span><h3>{a}</h3><p>{b}</p></article>' for i,(a,b) in enumerate([('Tell us your plans','Choose a service or send us your inspiration on WhatsApp.'),('Talk through the details','Discuss your look, the appointment time and the final price.'),('Make time for yourself','Visit the salon once your appointment has been confirmed.')]))+'</div></section>'
faq='<section class="section faq">'+heading('A FEW HELPFUL ANSWERS','Before you<br><em>say hello.</em>')+'<div class="faq-list">'+''.join(f'<details class="reveal"><summary>{q}<span>+</span></summary><p>{a}</p></details>' for q,a in [('Is this salon only for ladies?','Yes. Anjali Super Salon and Training Centre is exclusively for ladies, including its beauty training enquiries.'),('Can I enquire about bridal makeup?','Yes. Choose Bridal makeup and share your event date, preferred look and questions. The salon will discuss availability and pricing with you.'),('Do you offer makeup and haircut training?','Yes. Ask about makeup artistry, haircut and styling, or beauty and salon essentials. Confirm the current syllabus, fees, batch availability and duration directly with the centre.'),('Does sending an enquiry confirm my booking?','No. WhatsApp opens with your enquiry; the salon will reply to confirm the appointment or training details.'),('Where is the salon?','The salon is in Abhayapuri, Assam. Ask on WhatsApp for the exact address and directions before your visit.')])+'</div></section>'
pages={
'home':hero+'<div class="category-strip"><span>LADIES SALON</span><span>HAIR & STYLING</span><span>MAKEUP & BEAUTY</span><span>PROFESSIONAL TRAINING</span></div>'+intro+'<section class="section">'+heading('THE SALON EDIT','Good hair.<br><em>A gorgeous feeling.</em>','Everyday grooming, occasion makeup and everything in between.')+servicecards()+ '</section>'+pricing()+training()+process+faq+'<section class="section" id="enquiry">'+contactform()+'</section>',
'services':'<section class="page-head"><span class="eyebrow">THE LADIES SALON</span><h1>Your beauty.<br><em>Our attention.</em></h1><p>Explore hair, makeup and beauty care. Choose a service to start a personal enquiry.</p></section><section class="section compact">'+servicecards()+'</section>'+pricing()+process+'<section class="section">'+contactform()+'</section>',
 'training':'<section class="page-head"><span class="eyebrow">BEAUTY TRAINING FOR WOMEN</span><h1>Learn the craft.<br><em>Create your future.</em></h1><p>Explore practical learning in makeup, haircutting and beauty care at Anjali Training Centre.</p>'+btn('Discuss a training course','course','Help me choose a course')+'</section>'+training()+'<section class="section intro">'+heading('START WITH A CONVERSATION','Your learning journey<br><em>begins here.</em>')+'<div class="intro-copy reveal"><p>Whether you are starting from the basics or exploring a specific skill, tell us your interests and learning goals.</p><ul class="checklist"><li>Discuss your current skill level</li><li>Ask for the course syllabus and practical format</li><li>Confirm fees, duration and batch timings</li><li>Clarify any certificate details before enrolling</li></ul>'+btn('Ask about upcoming batches','course','Upcoming batches')+'</div></section>'+faq+'<section class="section">'+contactform()+'</section>',
'about':'<section class="page-head"><span class="eyebrow">ANJALI / ABHAYAPURI</span><h1>For the woman<br><em>behind every look.</em></h1><p>A ladies parlour and training centre, bringing personal beauty care and creative learning together.</p></section>'+intro+'<section class="section about-feature"><div class="about-photo reveal from-left"><img src="/assets/stylist.webp" loading="lazy" alt="Editorial portrait of an Indian hairstylist holding scissors" width="1024" height="1536"><span>HAIR. BEAUTY. LEARNING.</span></div><div class="reveal from-right"><span class="eyebrow">OUR FOCUS</span><h2>A space for beauty.<br><em>A place to learn.</em></h2><p>At Anjali, salon care and beauty training sit side by side. Come in for a haircut, prepare for a celebration, or explore the techniques behind a finished look.</p><p>Our services and training are for ladies. Every enquiry starts with understanding what you need and discussing the next step with you.</p>'+btn('Plan your visit','appointment')+'</div></section>'+process+'<section class="section">'+contactform()+'</section>',
'contact':'<section class="page-head"><span class="eyebrow">CONTACT & ENQUIRIES</span><h1>A fresh look is<br><em>one hello away.</em></h1><p>Salon appointment, bridal enquiry or beauty training — tell us how we can help.</p></section><section class="section compact">'+contactform()+'</section><section class="section location">'+heading('COME SAY HELLO','Find us in<br><em>Abhayapuri, Assam.</em>','Ask us for the exact salon location before travelling.')+'<div class="location-actions">'+btn('Ask for salon directions','general','Directions to Anjali Super Salon')+btn('Open Abhayapuri map',href='https://www.google.com/maps/search/?api=1&query=Abhayapuri%2C%20Assam',cls='button outline')+'</div><iframe title="Map showing Abhayapuri, Assam, not the exact salon location" src="https://maps.google.com/maps?q=Abhayapuri%2C%20Assam&t=&z=13&ie=UTF8&iwloc=&output=embed" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe></section>'+faq}
nav=[('home','Home','/'),('services','Services','/services/'),('training','Training','/training/'),('about','About','/about/'),('contact','Contact','/contact/')]
for key,body in pages.items():
    html='<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#171516"><title>'+('Anjali Super Salon & Training Centre | Ladies Salon in Abhayapuri' if key=='home' else key.title()+' | Anjali Super Salon & Training Centre')+'</title><meta name="description" content="Ladies salon and beauty training in Abhayapuri, Assam. Enquire about haircuts, makeup, bridal looks and courses. Call 9101035255."><link rel="icon" href="/assets/favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="/assets/style.css"><script defer src="/assets/app.js"></script></head><body><a class="skip-link" href="#main">Skip to content</a><div class="cursor" aria-hidden="true"></div><div class="topbar"><span>LADIES SALON & TRAINING CENTRE</span><div><span>Abhayapuri, Assam</span><a href="tel:+919101035255">9101035255</a></div></div><header><a class="brand" href="/" aria-label="Anjali Super Salon home"><span>Anjali<span class="brand-dot">.</span></span><small>SUPER SALON & TRAINING CENTRE</small></a><button class="menu-toggle" aria-label="Open navigation" aria-expanded="false" aria-controls="navigation"><span></span><span></span></button><nav id="navigation">'+''.join(f'<a href="{url}" {"aria-current=page" if k==key else ""}>{label}</a>' for k,label,url in nav)+btn('LET’S SHINE','appointment',cls='button nav-cta')+'</nav></header><main id="main">'+body+'</main><footer><div class="footer-top"><a class="brand" href="/"><span>Anjali.</span><small>SUPER SALON & TRAINING CENTRE</small></a><p>Hair, beauty and a little<br>time for yourself.</p>'+btn('Let’s talk','general',cls='button outline')+'</div><div class="footer-bottom"><p>© '+str(2026)+' Anjali Super Salon and Training Centre.<br>Exclusively for ladies · Abhayapuri, Assam</p><div>'+''.join(f'<a href="{url}">{label}</a>' for _,label,url in nav)+'</div><a href="tel:+919101035255">9101035255</a></div></footer>'+btn('<span aria-hidden="true">◉</span><span>WhatsApp</span>','general',cls='whatsapp-sticky')+'</body></html>'
    path=root/('index.html' if key=='home' else key+'/index.html');path.parent.mkdir(parents=True,exist_ok=True);path.write_text(html)
(root/'assets'/'catalog.json').write_text(json.dumps({'services':[s[0] for s in services],'courses':[c[0] for c in courses]}))
(root/'assets'/'favicon.svg').write_text('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 40 40"><rect width="40" height="40" rx="10" fill="#d74b70"/><text x="20" y="29" text-anchor="middle" font-family="Georgia" font-size="31" fill="white">A</text></svg>')
(root/'robots.txt').write_text('User-agent: *\nAllow: /\n')
